### ISSUE TITLE
请问下命令行执行语句是怎么写的？

### ISSUE THREAD

**Issue by yumeiqiang** [orestonce/Ip2regionTool#1]
命令行的执行语句是怎么写的？

**Comment by orestonce** [comment]
````
./cmd TxtToDb --txt input.txt --db output.db
./cmd DbToTxt --db input.db --txt output.txt
````

**Comment by yumeiqiang** [comment]
> ```
> ./cmd TxtToDb --txt input.txt --db output.db
> ./cmd DbToTxt --db input.db --txt output.txt
> ```

大佬是执行main.go这个文件嚒 go run main.go TxtToDb --txt ip.merge.txt  --db output.db

**Comment by orestonce** [comment]
是的
