### ISSUE TITLE
ip2regionTool可以支持shell方式吗

### ISSUE THREAD

**Issue by pushiwuhua7** [orestonce/Ip2regionTool#3]
你好，请问ip2regionTool可以支持shell方式吗？

**Comment by orestonce** [comment]
可以， cmd/main.go 就是 shell的执行入口，[release页面](https://github.com/orestonce/Ip2regionTool/releases) 提供linux和mac版本的可执行文件。

**Comment by pushiwuhua7** [comment]
> 

谢谢！
